### ISSUE TITLE
硬件资源问题

### ISSUE THREAD

**Issue by crazyFoolLh** [lukecq1231/kim#14]
您好，我在32核cpu和64G内存的服务器上运行您的代码，在训练两个小时左右就中断了，应该是内存不足，服务器强制中断了。
请问在cpu下可以运行成功吗，需要多少内存才可以？还有您是在GPU下运行的吗，如果要在GPU下运行，需要什么样的GPU配置，多少显存才可以。
希望您能给予解答，万分感谢！

**Comment by Lee-handsome** [comment]
你好，问题解决了吗

**Comment by crazyFoolLh** [comment]
解决了，我在具有12G显存的GPU下训练的模型复现了实验结果，差不多40分钟一个epoch。

**Comment by Lee-handsome** [comment]
> 解决了，我在具有12G显存的GPU下训练的模型复现了实验结果，差不多40分钟一个epoch。

在12G显存的GPU下训练就不会内存溢出吗？ 实验运行一共运行到多少个epoch

**Comment by crazyFoolLh** [comment]
> > 解决了，我在具有12G显存的GPU下训练的模型复现了实验结果，差不多40分钟一个epoch。
> 
> 在12G显存的GPU下训练就不会内存溢出吗？ 实验运行一共运行到多少个epoch

我在12G显存的GPU下可以很好的运行，内存不会溢出，我运行了差不多10个epoch，基本达到了论文中的实验效果，如果运行更多应该效果会更好。
